### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by miljosh68** [jepiqueau/angular-sqlite-app-starter#1]
The starter app works on Android (Didn't try it on iOS). I can see (using Device File Explorer in Android Studio) that, the app creates two databases. But, when I use the plugin in my Ionic, Capacitor app, it doesn't work. The database is not created. 

I created Ionic Capacitor using usual method (`ionic start myApp blank --type=ionic-angular`) and then followed the instructions given on the starter app page. But, my app could not create database. So, I deleted my node_modules directory, package.json and the lock files. Copied and pasted the package.json and the lock files from starter app and did npm install. Even after using the same package.json file, I was not able to create a database. 

There is a thread in Ionic Forums (https://forum.ionicframework.com/t/cant-get-sqlite-plugin-to-work-in-my-app/185622) that has similar issue. After going through the same, I thought of creating an issue here to seek help. 

Any help is appreciated.

**Comment by jepiqueau** [comment]
@miljosh68  You certainly forgot  to modify your MainActivity file  an then you are running with the browser plugin and do not see any database created. just go to the MainActivity file an change it with 
```
package YOUR PACKAGE;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;

import com.jeep.plugin.capacitor.CapacitorDataStorageSqlite;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(CapacitorDataStorageSqlite.class);
    }});
  }
}

``` 
or if you have done it check that you have named the plugin ```CapacitorDataStorageSqlite``` and not ``` CapacitorDataStorageSQLite```  . Normally after this it should work. otherwise save your project on github and i will check. Thanks anyhow to use the plugin

**Comment by jepiqueau** [comment]
@miljosh68  Sorry i made a confusion you are talking about capacitor-sqlite and not capacitor-data-storage-sqlite so your MainActivity file should be :
```
package YOUR PACKAGE;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;


import com.jeep.plugin.capacitor.CapacitorSQLite;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);

      add(CapacitorSQLite.class);
    }});
  }
}

```
in that case  the plugin is ```CapacitorSQLite``` and not ```CapacitorSqlite```  Hope this help and solve the issue

**Comment by miljosh68** [comment]
Thank you so much. IT WORKS.

**Comment by jepiqueau** [comment]
@miljosh68 You are welcome, that was written in the README.md under Android chapter

**Comment by miljosh68** [comment]
Yes, I had gone through it but thought that it is done automatically (just
like the other automated tasks). Thank you once again.
--
In every walk with nature one receives far more than he seeks - John Muir

**Comment by jepiqueau** [comment]
@miljosh68 
Hi,
I do not quite understand what you mean by "thought that it is done automatically (just
like the other automated tasks). » can you be more explicit.
The idea for having an import and later an export to json will allow synchronization between a server based database and the device database, but the synchronization process should be in my view done in the application not by the plugin. It will allow also to export the current device database and change the database schema and reload the data in the new database when no connection to server based database but here also the app will manage this.  Are we on a same line?

**Comment by miljosh68** [comment]
@jepiqueau 
Well, what I meant by 'done automatically' was about the step of adding the 'import' statement in the MainActivity.java file. It was not related to any database stuff. Hope this clarifies the issue.

**Comment by jepiqueau** [comment]
@miljosh68 Unfortunately this is not done automatically. So you have to do it for each new app
