### ISSUE TITLE
Getting error - "Type 'null' is not assignable to type 'SQLiteDBConnection'."

### ISSUE THREAD

**Issue by pratiksan45** [jepiqueau/angular-sqlite-app-starter#10]
I am stuck at this code statement .
 const **db**: SQLiteDBConnection = await this.sqlite.createConnection(database, encrypted, mode, version);

The below error is shown for the 'db' - 
Type 'SQLiteDBConnection | null' is not assignable to type 'SQLiteDBConnection'.
  Type 'null' is not assignable to type 'SQLiteDBConnection'.ts(2322)

**Comment by jepiqueau** [comment]
@pratiksan45 Which platform are you using ? which angular-sqlite-app-starter version (master branch, refactor branch, 2.4.x branch) ?
