### ISSUE TITLE
Wrong parsing data in values array parameter in query function

### ISSUE THREAD

**Issue by Ahmedesayed** [jepiqueau/angular-sqlite-app-starter#12]
There is a problem in parsing data in query function , if you pass a number in values array it will be parsed as a string which will make a wrong query

**Comment by parthnayak7448** [comment]
Yes, felt same problem it change the return datatype or passed datatype

**Comment by jepiqueau** [comment]
@Ahmedesayed @parthnayak7448 This has been fixed (issue #110 of `@capacitor-community/sqlite`) so i close the issue
