### ISSUE TITLE
Unable to use this plugin in an electron app

### ISSUE THREAD

**Issue by berengere13** [jepiqueau/angular-sqlite-app-starter#13]
Hi,

I have an electron app in angular with ionic; I use @capacitor-community/electron and @capacitor-community/sqlite ( so your plugin too).

I use Angular 11, Electron 10.3.1, @journeyapps/sqlcipher 5.2.0, Node v14.17.0.

I can't open the electron app without rename electron\node-module\@journeyapps\sqlcipher\lib\binding\napi-v**6**-win32-ia32 to ..\napi-v**3**-win32-ia32 .

Once rename, electron app could be open. But when I package electron app in the same PC ,I can't use the .exe generated. The packaging is going well, but the app generated is a blank app with error : 

![image](https://user-images.githubusercontent.com/6480292/122436528-2e613300-cf99-11eb-9edb-bb4995dcca2b.png)

I don't know why the pakage changes ( napi-v6-win32-**x64**). I tried to add manually this package in electron\node_modules.

I don't know if it's a version's problems. I can't package either this exemple project.

Can anyone help me please ?

**Comment by jepiqueau** [comment]
@berengere13 thanks for using the plugin I am currently travelling and not able to make the test of packaging the app. I will have a look and revert as soon as I can. In a meantime is someone else can help he is welcome

**Comment by jepiqueau** [comment]
@berengere13 It seems that we have to wait @capacitor-community/electron v4 and @capacitor/core@3.2.0 before i can start re-implementing this plugin. i am sorry for this but nothing i can do. Follow this in the `@capacitor-community/sqlite` releases. So i close the issue
