### ISSUE TITLE
Lastest version of sqlite and jeep-sqlite cause error when open database on browser

### ISSUE THREAD

**Issue by kyoz** [jepiqueau/angular-sqlite-app-starter#26]
With latest version of:
    "@capacitor-community/sqlite": "3.5.1-2",
    "jeep-sqlite": "1.5.1",

This project doesn't work on browser (work fine on mobile), and print some error like:

```
core.mjs:6485 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'apply')
TypeError: Cannot read properties of undefined (reading 'apply')
    at e.stackAlloc (jeep-sqlite.entry.js:2661:506)
    at e.onRuntimeInitialized (jeep-sqlite.entry.js:2561:213)
    at a (jeep-sqlite.entry.js:2663:432)
    at dd (jeep-sqlite.entry.js:2664:321)
    at cd (jeep-sqlite.entry.js:2662:343)
    at a (jeep-sqlite.entry.js:2650:176)
    at b (jeep-sqlite.entry.js:2650:197)
    at push.23484._ZoneDelegate.invoke (zone.js:409:1)
    at Object.onInvoke (core.mjs:25592:1)
    at push.23484._ZoneDelegate.invoke (zone.js:408:1)
    at resolvePromise (zone.js:1262:1)
    at zone.js:1169:1
    at zone.js:1185:1
    at push.23484._ZoneDelegate.invoke (zone.js:409:1)
    at Object.onInvoke (core.mjs:25592:1)
    at push.23484._ZoneDelegate.invoke (zone.js:408:1)
    at push.23484.Zone.run (zone.js:169:1)
    at zone.js:1326:1
    at push.23484._ZoneDelegate.invokeTask (zone.js:443:1)
    at Object.onInvokeTask (core.mjs:25579:1)
```

The current version of these package work fine but when I tried to update them to latest, this error happen.

I have tried to update typescript, capacitor/core...etc and other things but still no luck. even with a brand new project have everything update date.

Doesn't know what cause it 🤔

**Comment by jepiqueau** [comment]
@kyoz thanks to report i saw this error with the latest version but i cannot figure out what happen. When i test the latest release with solidjs it works fine. I do not have the time right now to look at it i am busy refurbishing my house.

**Comment by kyoz** [comment]
It's ok @jepiqueau , I'm trying to debug and find out what cause the issue. It's maybe something relate to core packages and versions. When trying this repo with exact versions of packages in package.json (remove all ~ and ^), also remove package-lock.json and reinstalled everything. The same problem occur with:
  - "@capacitor-community/sqlite": "3.4.2-2",
  -  "jeep-sqlite": "1.3.7",

I'll investigate more and let you know if I found something.

**Comment by jepiqueau** [comment]
@kyoz thanks you for this. If you find the reason make a PR and i will merge it

**Comment by kyoz** [comment]
Hey bro @jepiqueau , just found it. It turn out that's the problem of new sql.js version. everything work fine with sql.js@1.6.2. But with newer versions it start cause error on browser. I don't have time to digging to find out what is the real culprit right now in sql.js.

But since we found the problem I think we just have to change [this line](https://github.com/jepiqueau/jeep-sqlite/blob/7db7b7c582dd530429c42b84ae5f4ef9c9f4dd2f/package.json#L29), by remove ^. It'll ensure jeep-sqlite to use exact sql.js@1.6.2 and everything work fine.

Please give it a check when you have time and close this issue. for now I can continue development with:

```
npm install --dev sql.js@1.6.2
```

**Comment by jepiqueau** [comment]
@kyoz thanks for your contribution well done at l'est we know what to do and whzt we have to look at.

**Comment by kyoz** [comment]
Thanks @jepiqueau, I'm trying this along with @capacitor/sqlite. At this time a can confirm the error is come from sql.js version. But let me digging a little bit to see is there any problem. I'll open a PR when I'm sure everything is working without any problem 😄

**Comment by jepiqueau** [comment]
@kyoz with the new release of sql.js have you copy the new wasm file to the asset folder of your app after removing rhe old version

**Comment by kyoz** [comment]
@jepiqueau , I copy new was file every time I serve the web, just as this repo scripts in `package.json`. At first, I do think the problem come from wasm file too, so I'v tried to clear npm cache and do a fresh install, but the problem is still there.

The demo work because in package-lock.json, it using sql.js@1.6.2. And locked install that version. With other project when we install `jeep-sqlite`, because of the `^` prefix, it'll install a newer version of sql.js and then the problem came.

**Comment by KGHawes-DeLess** [comment]
Just FYI for anyone facing a similar issue...I was able to work around the sql.js issue using https://www.npmjs.com/package/npm-force-resolutions.

**Comment by jepiqueau** [comment]
@KGHawes-DeLess i just published 1.5.3 which strictly use sql.js@1.6.2 can you test and report

**Comment by jepiqueau** [comment]
@kyoz see my comment above

**Comment by kyoz** [comment]
Hi @jepiqueau , I just tested. Thank you very much.  I'll close this issue since it has been fixed.

**Comment by jepiqueau** [comment]
@kyoz thanks for your quick test and report good luck with your dev
