### ISSUE TITLE
Not able to debug in chrome

### ISSUE THREAD

**Issue by stealthAngel** [jepiqueau/angular-sqlite-app-starter#30]
Hello, I tried to debug with visual studio code, but for some reason webpack is not showing.

![image](https://user-images.githubusercontent.com/23656202/177803219-dda2a7c9-6481-4882-b469-0a78399603e2.png)

With a normal ionic angular project I have

![image](https://user-images.githubusercontent.com/23656202/177803406-c3f1cd8b-9773-4ebd-9132-a9f0523b6179.png)

which allows debugging, any idea?

**Comment by stealthAngel** [comment]
I made a pull request solving this issue.

**Comment by jepiqueau** [comment]
@stealthAngel i saw it but i think it should be made in a way that when you are in development mode it should be as you suggest but if you are in production mode it should be as it was. If you have time to look into it please do so and make a new PR

**Comment by stealthAngel** [comment]
I will test it

**Comment by stealthAngel** [comment]
![image](https://user-images.githubusercontent.com/23656202/180992707-5c1cd4bc-35c6-43f4-9c6e-97ac0d8f74fd.png)

![image](https://user-images.githubusercontent.com/23656202/180992920-de54f848-826f-4349-a607-b538f1355c5e.png)


ionic serve --prod 

ionic serve --configuration production

it overrides the default behavior.

Didn't test it on the phone.

**Comment by jepiqueau** [comment]
@stealthAngel i merge the PR. Can you test and close the issue

**Comment by stealthAngel** [comment]
Yes definitely,
