### ISSUE TITLE
On page refresh the sqlite isn't being loaded if you are on another page

### ISSUE THREAD

**Issue by stealthAngel** [jepiqueau/angular-sqlite-app-starter#35]
https://github.com/jepiqueau/react-sqlite-app-starter/issues/10

It's the same problem as this ticket. I'm trying to find a way around it. It's difficult to solve.

**Comment by jepiqueau** [comment]
@stealthAngel i will have a look later

**Comment by jepiqueau** [comment]
@stealthAngel  this is fix in release 3.5.2-dev3. Modifications in `main.ts` and in `app.component.ts`

**Comment by jepiqueau** [comment]
@stealthAngel after test please can you close the issue

**Comment by stealthAngel** [comment]
Will do it today

**Comment by stealthAngel** [comment]
tested it on different pages it works

**Comment by stealthAngel** [comment]
![image](https://user-images.githubusercontent.com/23656202/181118806-5a1ce732-03c5-43f6-9920-723c3fc8147b.png)


Unfortunately, I found a bug while testing when I was coding with this app.

To reproduce:

in `hometests.page.ts `

`export class HomeTestsPage implements OnInit {`


```

  async ngOnInit() {
    this.insertData();
  }

  async insertData() {
    const db = await this._sqlite.createConnection("db_issue9", false, "no-encryption", 1);
    await db.open();

    //insert a test into test
    let query = `
    insert into test (name) values ("test")
    `;
    console.log(query);
    const res: any = await db.execute(query);
    console.log(`res: ${JSON.stringify(res)}`)

    //get test data and log it
    var data: any = await db.query("select * from test");
    console.log(data);


    await this._sqlite.closeConnection("db_issue9");
  }
```

`app.component.ts`

change line 71 to `console.error(`Error: ${err}`);` so you can see the error more clearly.

Then change in 4 places "db_issue9" string to another string e.g. "db_issue93".

2 in `hometests.page.ts` and another 2 in `app.component.ts`


https://github.com/stealthAngel/angular-sqlite-app-starter/tree/errorstartup

**Comment by stealthAngel** [comment]
I fixed itwill make a pr later

**Comment by jepiqueau** [comment]
@stealthAngel I merge the PR . Can you test and close the issue

**Comment by stealthAngel** [comment]
I thought it was wanted behaviour, it's because of this,

https://github.com/jepiqueau/angular-sqlite-app-starter/blob/master/src/app/test/hometests/hometests.page.ts


```
constructor(private _sqlite: SQLiteService,
    private _detailService: DetailService,
    private _ref: ChangeDetectorRef) {
    this.platform = Capacitor.getPlatform();
    const mConfig = config.plugins && config.plugins.CapacitorSQLite ? config.plugins.CapacitorSQLite : null;

    if (this.platform === "android" && mConfig != null) {
      this.isBiometric = mConfig.androidBiometric && mConfig.androidBiometric.biometricAuth
        ? mConfig.androidBiometric.biometricAuth : false;
    }
    if (this.platform === "ios" && mConfig != null) {
      this.isBiometric = mConfig.iosBiometric && mConfig.iosBiometric.biometricAuth
        ? mConfig.iosBiometric.biometricAuth : false;
    }
    console.log(`>>>>> in Home constructor ${this.isBiometric}`)
  }
```


in HTML:

`<div *ngIf="isDisplay">`

**Comment by jepiqueau** [comment]
@stealthAngel no it was not . Biometric is to protect your application with a biometric login (finger or face) so before receiving the event from the listener no buttons should be shown so the isDisplay parameter was made for this. The biometric login is ste in the capacitor.config.ts.

**Comment by stealthAngel** [comment]
Looking into it now

**Comment by stealthAngel** [comment]
![image](https://user-images.githubusercontent.com/23656202/184474926-2dc34e18-3b20-4775-83c0-3798004610a6.png)


I have no idea tbh. 

I reverted to the state it was in the beginning and it still doesn't show.

In home test certain conditions have to be met. I have to have a good look to really understand whats going on there.

**Comment by jepiqueau** [comment]
@stealthAngel what i try to explain to you is that the button product  should be under the <div *ngIf="isDisplay"> like all the other. And as you have in the capacitor-congig.ts androidBiometric.biometricAuth set to true nothing should be visible before you log with the biometrics. If you do not want to use the biometric set androidBiometric.biometricAuth to false in the capacitor.config.ts and everything should be visible like on iOS. Hope this clarify
